name: ChatColors
version: '${project.version}'
main: com.tqqn.chatcolors.ChatColors
api-version: '1.20'
load: STARTUP
commands:
  chatcolor:
    description: Choose a chatcolor
    usage: /<command>
    permission: chatcolor.menu